Make GPUImage Dependency Again
mousetraps/LFLiveKit pull request #2
Opened 2017-11-22 23:14 UTC by davidswi

This PR adds GPUImage as a dependency to the podspec for LFLiveKit and removes the private copy of GPUImage.

2017-11-23 01:00 UTC, mousetraps requested changes
Minor comments, and looks good after that!

2017-11-23 01:00 UTC, mousetraps commented on LFLiveKit.podspec
> +  s.dependency 'GPUImage'
How does CocoaPods handle versioning of dependencies?

2017-11-23 01:00 UTC, mousetraps commented on LFLiveKit.podspec
> +  s.source       = { :git => "git@github.com:davidswi/LFLiveKit.git", :branch => "davids/gpuimage-as-dependency" }
This should be reverted

2017-11-28 20:21 UTC, davidswi commented on LFLiveKit.podspec
> +  s.dependency 'GPUImage'
You can add a version specifier.

2017-11-28 20:22 UTC, davidswi commented on LFLiveKit.podspec
> +  s.dependency 'GPUImage'
From Stack Overflow, a good discussion about dependencies:
https://stackoverflow.com/questions/22447062/how-do-i-create-a-cocoapods-podspec-that-has-a-dependency-that-exists-outside-of

2017-11-28 22:14 UTC, mousetraps requested changes
minor comment, looks good after that!

2017-11-28 22:14 UTC, mousetraps commented on LFLiveKit.podspec
> +  s.version      = "2.6+av-sync-gpuimage-dep"
should be reverted

2017-11-28 22:18 UTC, merged